#!/usr/bin/env php
<?php

/**
 * (c) 2018 Douglas Reith.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
declare(strict_types=1);

require __DIR__.'/vendor/autoload.php';

// Console classes
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Output\ConsoleOutput;
use Symfony\Component\Console\Logger\ConsoleLogger;
use Reith\ToyRobot\Console\Place;
use Reith\ToyRobot\Console\BusHelper;

// For annotations
use Doctrine\Common\Annotations\AnnotationRegistry;

// Table
use Reith\ToyRobot\Domain\Space\Table;

// Persistence
use Reith\ToyRobot\Infrastructure\Persistence\FileRobotStore;
use Reith\ToyRobot\Infrastructure\Persistence\RobotRepository;

// Buses
use Reith\ToyRobot\Infrastructure\Bus\CommandBus;
use Reith\ToyRobot\Infrastructure\Bus\QueryBus;

// Command and query handlers
use Reith\ToyRobot\CommandHandler\RobotPlacer;
use Reith\ToyRobot\CommandHandler\RobotMover;
use Reith\ToyRobot\QueryHandler\FindRobots;

/**
 * A lot of the following work would normally be delegated
 * to a DI container. Doing it directly here because it is
 * a small app
 */

// Set up the handler Subscribe annotation
AnnotationRegistry::registerFile(
    __DIR__ . '/src/Reith/ToyRobot/Messaging/Annotation/Subscribe.php'
);

// App logging
$output = new ConsoleOutput();
$logger = new ConsoleLogger($output);

// Set up the 5x5 Table
$table = Table::create(5);

// Get a File Robot store - use temp dir as a base path for storage
$basePath = sys_get_temp_dir();
$store = FileRobotStore::getStore($basePath, $logger);

// Pass to the repository
$repository = new RobotRepository($store);

// Create the command and query handlers
$robotPlacer = new RobotPlacer($table, $repository, $logger);

// Now the buses
$commandBus = (new CommandBus($logger))
    ->registerHandler($robotPlacer)
;

// Set up the console
$application = new Application('Reith ToyRobot', '0.0.1');
$application->add(new Place());

$busHelper = (new BusHelper())
    ->setCommandBus($commandBus)
;

$application->getHelperSet()->set($busHelper);

$application->run(null, $output);
