#!/usr/bin/env php
<?php

/**
 * (c) 2018 Douglas Reith.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
declare(strict_types=1);

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Reith\ToyRobot\Console\Place;
use Reith\ToyRobot\Console\BusHelper;
use Reith\ToyRobot\Infrastructure\Bus\CommandBus;

$application = new Application();

$application->add(new Place());
$busHelper = new BusHelper(new CommandBus([]), new CommandBus([]));
$application->getHelperSet()->set($busHelper);

$application->run();
